language: python
install:
    pip install -r requirements.txt
jobs:
  - stage: first
    name: "Testing dirst task"
    python: "3.6"
    script:
        pytest tests
stages: 
  -name: first
    if: branch = Task1
notifications:
  email: vasiagoloparov@gmail.com
